### ISSUE TITLE
Remove try_decode_partial

### ISSUE THREAD

**Issue by punchfox** [spotify/spotify-json#19]
Can we remove `try_decode_partial`? I don't really understand when we would want to use this? I do see several uses of it in the Spotify codebase, but I don't see why those places don't just use `try_decode`.

Is it a common use case to expect the correctly formatted JSON to followed by garbage that should not be parsed? This seems dangerous, since we support parsing plain JSON values, not just JSON objects, e.g., parsing the correctly formatted JSON `123` followed by the garbage `456`, resulting in the number 123456, not 123.

**Comment by pereckerdal** [comment]
@punchfox I agree. Do you know if any of the places in the Spotify code base that use it actually need it?

**Comment by punchfox** [comment]
Implemented in #21. I will check uses in our codebase before merging.
