### ISSUE TITLE
Simplify the encoded_value type

### ISSUE THREAD

**Issue by punchfox** [spotify/spotify-json#20]
We have found that it is a bit too cumbersome to use the `encoded_value<T>` struct. It has several limitations in some of our common uses cases:

- It is often not very interesting to know how the data is stored in the value
- When the caller wants a `std::string` it can just call `json::encoded` instead of `json::encoded_value`
- Creating an `encoded_value` with the intention of writing to another JSON string requires an extra copy of the encoded JSON (`encode_context` → `std::string` → `encode_context`)
- `json::encode_value` is unsafe when used incorrectly (`json::encode<json::ref>(...)`)
- It is difficult to write an function that takes an encoded value, since the value has the storage type in a template parameter (`encoded_value<std::string>`, `encoded_value<ref>` or `encoded_value<whatever>`?)

We would like the API to have the following characteristics:

- Safe
- Simple
- As fast as possible but not faster

I feel that the current variant of `encoded_value<T>` fails all three of those. 😢

I propose that we simplify the `encoded_value<T>` to just `encoded_value` (no `<T>`). The new version will always own the JSON data, but we don't allow the caller to `std::move` the storage out from it. The most common use case for this was to steal the underlying `std::string` value, but the caller can do that with `json::encode` anyway. The new type would allow the `json::encode_value` function to move the `encode_buffer` into the returned value, avoiding the extra copy mentioned above.

This would make the API safe and simple and in many cases fast. We should also let advanced users of the API avoid the copy completely when there is an opportunity for that. I propose that we introduce a new type `json_value_ref` that is similar to the `json_value` (the `any_value_t` codec should work with both types), but does not have its own storage of the JSON, just referring to another JSON buffer. The caller is then responsible for keeping the JSON buffer alive for as long as they need to use the encoded values.

By letting the `encoded_value` and `encoded_value_ref` types implicitly convert, the usage stays simple:

```c++
...
json::encoded_value save_some_state() const;
void restore_some_state(const json::encoded_value_ref &saved_state);
...
const auto saved_state = save_some_state();
restore_some_state(saved_state);
```

Compare this to today's situation:

```c++
...
json::encoded_value<> save_some_state() const;  // T is std::string
void restore_some_state(const json::encoded_value<> &saved_state);
...
const auto saved_state = save_some_state();  // Copying the JSON into a std::string
restore_some_state(saved_state);
```

or:

```c++
...
json::encoded_value<> save_some_state() const;  // T is std::string
void restore_some_state(const json::encoded_value<json::ref> &saved_state);
...
const auto saved_state = save_some_state();  // Copying the JSON into a std::string
restore_some_state(saved_state);  // Mismatching storage types
```

## Summary

~~`json::encoded_value<T>`~~
`json::encoded_value` and `json::encoded_value_ref`

**Comment by pereckerdal** [comment]
lgtm. How far away do you think we are from 1.0 after this?

**Comment by fxb** [comment]
Also seems sensible to me.
