### ISSUE TITLE
Remove `where` parameter from transform lambda

### ISSUE THREAD

**Issue by punchfox** [spotify/spotify-json#27]
**Version:** 1.0.0

The `transform_t` codec takes a function with two arguments to transform the decoded value. I propose that we remove the second parameter, `where`. It is there so that there is something to pass into the `decode_exception` constructor. It makes the function more _boilerplatey_ and also means that you cannot easily use transform functions not specifically written for our JSON library, e.g., using an `int2str` function that takes an `int` and returns a `std::string`.

The original use case for the `where` parameter can be handled by catching any `decode_exception` thrown by the transform function and just setting the where parameter as appropriate before re-throwning the exception.

**Comment by emil-e** [comment]
:+1:

**Comment by fxb** [comment]
+1

**Comment by pereckerdal** [comment]
Nice. I like it
