### ISSUE TITLE
Can we declare version 1.0?

### ISSUE THREAD

**Issue by punchfox** [spotify/spotify-json#29]
Is there anything more we need to do until we can call this version 1.0? We can definitely hold off on any additions until future versions. Are we happy with the interface and naming of the codecs and functions? Those are the things we cannot change later without breaking source compatibility.

**Comment by pereckerdal** [comment]
I say go!

**Comment by emil-e** [comment]
I agree, the last encoded value fixes did it for me.

**Comment by fxb** [comment]
Let's do it.

**Comment by punchfox** [comment]
I ran into a bug when porting some old code to this API, using it as more of a graph based API. Turns out that it is not possible right now to put an `encoded_value` in a `std::vector` and encode it using the `array_t` codec, because there is a static assertion in the codec that requires that the vector element type (`encoded_value`) is the same as the inner codec's object type (`encoded_value_ref`). I'm assuming that this is also the case for maps. We should be able to solve this with a different static assertion, since `encoded_value_ref` can implicitly convert to `encoded_value`. It should not lead to any changes in the public APIs, but we should fix it before declaring 1.0.0, because it makes it impossible to use for some simple use cases.

**Comment by pereckerdal** [comment]
@punchfox Instead of using `std::is_same`, do you think we could use two `std::is_convertible` assertions (one in each direction) instead?

**Comment by pereckerdal** [comment]
Another question: What should we do to make it 1.0.0? Add a git tag? Is that enough?

Also, after tagging it, should we announce it? Where? Add it to json.org? hacker news?

**Comment by pereckerdal** [comment]
@punchfox I'm working on a fix for the `is_same` issue

**Comment by punchfox** [comment]
@peck Great! Was gonna do it, but I think I will have lunch instead then. :smile:

A tag should be enough. Any fixes can be new patch versions. Will we support 1.x and 2.x at the same time in the future?

**Comment by pereckerdal** [comment]
@punchfox I think supporting two major versions in parallel will depend on the reason for the break and how widely adopted the library is. I would take that decision later

**Comment by punchfox** [comment]
I just published [version 1.0.0](https://github.com/spotify/spotify-json/releases/tag/v1.0.0).
